services:
  db:
    image: postgres:13
    container_name: db
    env_file: 
      - .env
    ports:
      - 5432:5432
    networks:
      - trans
    restart: always
  backend:
    build: ./Backend
    container_name: backend
    depends_on:
      - db
    env_file: 
      - .env
    ports:
      - 3001:3001
      - 5555:5555
    networks:
      - trans
    volumes:
      - ./Backend:/trans
      - /trans/node_modules
    restart: always
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/trans
      - /trans/node_modules
    networks:
      - trans
    restart: always


networks:
  trans:
    name: trans
    driver: bridge
